name: Build

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17

      - name: Install Android SDK
        run: ./.github/android-sdk.sh

      - uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: true

      - name: Build with Gradle
        run: ./gradlew build --stacktrace
