name: Publish Release

on:
  push:
    tags:
      - '**'

jobs:
  publish:

    runs-on: ubuntu-latest
    if: github.repository == 'gabrielittner/renderer'

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Install Android SDK
        run: ./.github/android-sdk.sh

      - name: Get release notes
        run: |
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$(awk '/^## ${{ github.ref_name }}/{flag=1;next}/^## /{flag=0}flag' CHANGELOG.md)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Set version for tag
        run: |
          echo "ORG_GRADLE_PROJECT_VERSION_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - uses: gradle/actions/setup-gradle@v4

      - name: Publish
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_SIGNING_PASSWORD }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ env.RELEASE_NOTES }}
